site_name: Infrastructure Engineering Hub
docs_dir: docs

theme:
  name: material

plugins:
  - search
  - ezlinks

nav:
  - Hub: 00-index/01-infrastructure-engineering-hub.md
  - Workspace: 10-workspace-config/10-workspace-config.md
  - Base Infrastructure:
    - PostgreSQL: 20-base-infrastructure/20-postgresql.md
    - Envoy Gateway: 20-base-infrastructure/21-envoy-gateway.md
    - Keycloak: 20-base-infrastructure/22-keycloak-oidc.md
    - MailDev: 20-base-infrastructure/23-maildev.md
  - Django Template: 30-django-service-template/30-django-service-template.md